server:
  port: 8080

spring:
  application:
    name: question-chooser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.240:32306/question_chooser?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  mapper-locations:
    - "classpath*:mappers/**/*.xml"

knife4j:
  enable: true
  openapi:
    title: question-chooser官方文档
    description: "question-chooser官方文档"
    email: e_mail4gxf@163.com
    concat: 生如夏花
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      question-chooser:
        group-name: question-chooser
        api-rule: package
        api-rule-resources:
          - com.fly.test
